// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnMX8NbwSyDGjhup1JgIC0akqq4m9HDcg',
    appId: '1:1082441295455:web:92238aaa45f0f840571dea',
    messagingSenderId: '1082441295455',
    projectId: 'hclcafe-2a95b',
    authDomain: 'hclcafe-2a95b.firebaseapp.com',
    databaseURL: 'https://hclcafe-2a95b-default-rtdb.firebaseio.com',
    storageBucket: 'hclcafe-2a95b.appspot.com',
    measurementId: 'G-FNXSGPCKJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEiLXtASRXD8ohtm0MEMc3NWSSuohoaCE',
    appId: '1:1082441295455:android:ace7c8712347bd5a571dea',
    messagingSenderId: '1082441295455',
    projectId: 'hclcafe-2a95b',
    databaseURL: 'https://hclcafe-2a95b-default-rtdb.firebaseio.com',
    storageBucket: 'hclcafe-2a95b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHtnTNbDJXG0Mbq-jTsI5ou5r8fhSpckM',
    appId: '1:1082441295455:ios:b5ce6cb37e86cc43571dea',
    messagingSenderId: '1082441295455',
    projectId: 'hclcafe-2a95b',
    databaseURL: 'https://hclcafe-2a95b-default-rtdb.firebaseio.com',
    storageBucket: 'hclcafe-2a95b.appspot.com',
    iosBundleId: 'com.cyberknights.hclcafeAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHtnTNbDJXG0Mbq-jTsI5ou5r8fhSpckM',
    appId: '1:1082441295455:ios:2c2f30019c74aff2571dea',
    messagingSenderId: '1082441295455',
    projectId: 'hclcafe-2a95b',
    databaseURL: 'https://hclcafe-2a95b-default-rtdb.firebaseio.com',
    storageBucket: 'hclcafe-2a95b.appspot.com',
    iosBundleId: 'com.cyberknights.hclcafeAdmin.RunnerTests',
  );
}
